In [88]:
import numpy as np
from zipfile import ZipFile 
import pandas as pd
  
# loading the temp.zip and creating a zip object 
with ZipFile('/Users/paarthdudani/Downloads/connectionist+bench+sonar+mines+vs+rocks.zip', 'r') as zObject: 
    zObject.extractall() 

df = pd.read_csv('/Users/paarthdudani/Desktop/All folders/Python files/Miscellaneous_NN/sonar.all-data', header=None)

df[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

### Binary classifier

In [89]:
# Extracting and processing the data 

dataset = df.to_numpy()

X = dataset[:,0:np.shape(dataset)[1]-1]
Y = dataset[:,-1]

# Binarizing the output.

for i in range(len(Y)):
    if  Y[i] == 'R':
        Y[i] = 1
    elif Y[i] == "M": 
        Y[i] = 0

### Building the NN

In [90]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.25, random_state = 1)

X_train = tf.convert_to_tensor(X_train, dtype=tf.float32)
X_test = tf.convert_to_tensor(X_test, dtype=tf.float32)
Y_train = tf.convert_to_tensor(Y_train, dtype=tf.float32)
Y_test = tf.convert_to_tensor(Y_test, dtype=tf.float32)

n = 20
error_array = np.zeros((n),)
for i in range(n):
    model = keras.Sequential(
        [keras.layers.Dense(60, activation = 'relu'),
        keras.layers.Dense(20, activation = 'relu'),
        keras.layers.Dense(10, activation = 'relu'),
        keras.layers.Dense(1, activation = 'sigmoid')]
    )

    model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

    model.fit(X_train, Y_train, epochs = 20, batch_size = 8)

    model.evaluate(X_test,Y_test)

    Y_pred = model.predict(X_test).reshape(-1)
    Y_pred = np.round(Y_pred)

    def accuracy_calculator(y_pred, y_test):
        counts = np.zeros((len(y_pred)),)
        for i in range(len(y_pred)):
            if y_pred[i] != Y_test[i]:
                counts[i] = 1
            else:
                continue
        return 1- sum(counts)/len(counts)

    from sklearn.metrics import confusion_matrix, classification_report
    print(classification_report(Y_test, Y_pred))

    print()
    print(accuracy_calculator(Y_pred,Y_test))

    error_array[i] = accuracy_calculator(Y_pred,Y_test)


error_array

Epoch 1/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 843us/step - accuracy: 0.6130 - loss: 0.6835 
Epoch 2/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step - accuracy: 0.6352 - loss: 0.6573
Epoch 3/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 773us/step - accuracy: 0.7493 - loss: 0.6272
Epoch 4/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 765us/step - accuracy: 0.6828 - loss: 0.6333
Epoch 5/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step - accuracy: 0.7139 - loss: 0.5973
Epoch 6/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - accuracy: 0.7337 - loss: 0.5841
Epoch 7/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step - accuracy: 0.7799 - loss: 0.5456
Epoch 8/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step - accuracy: 0.8042 - loss: 0.4909
Epoch 9/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - accuracy: 0.7977 - loss: 0.4625
Epoch 10/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8586 - loss: 0.4290
Epoch 11/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8668 - loss: 0.4055 
Epoch 12/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step 

KeyboardInterrupt: 

### Evaluation

In [ ]:
model.evaluate(X_test,Y_test)

Y_pred = model.predict(X_test).reshape(-1)
Y_pred = np.round(Y_pred)

def accuracy_calculator(y_pred, y_test):
    counts = np.zeros((len(y_pred)),)
    for i in range(len(y_pred)):
        if y_pred[i] != Y_test[i]:
            counts[i] = 1
        else:
            continue
    return 1- sum(counts)/len(counts)



from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(Y_test, Y_pred))

print()
print(accuracy_calculator(Y_pred,Y_test))

In [ ]:
a = np.random.randint(1,10,20)
b = np.random.randint(1,10,20)

def unbaised_sigma(input):
    return np.sqrt(sum((input - np.mean(input))**2))/(len(input)-1)

# unbaised_sigma()

In [ ]:
import matplotlib.pyplot as plt
mean_est = np.mean(error_array)

sigma_est = unbaised_sigma(error_array)

E = np.random.normal(mean_est,sigma_est, size=2000)

plt.hist(E, bins=100)

CI_95_lower_bound = mean_est - 1.96*sigma_est
CI_95_upper_bound = mean_est + 1.96*sigma_est

print(np.sort(E)[int(0.05*2000)],np.sort(E)[int(0.95*2000)])
print()
print(CI_95_lower_bound, CI_95_upper_bound)

In [143]:
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.25, random_state = 1)

X_train = tf.convert_to_tensor(X_train, dtype=tf.float32)
X_test = tf.convert_to_tensor(X_test, dtype=tf.float32)
Y_train = tf.convert_to_tensor(Y_train, dtype=tf.float32)
Y_test = tf.convert_to_tensor(Y_test, dtype=tf.float32)

n = 10
error_array = np.zeros((n),)
for i in range(n):
    model = keras.Sequential(
        [keras.layers.Dense(60, activation = 'relu'),
        keras.layers.Dropout(0.4),
        keras.layers.Dense(20, activation = 'relu'),
        keras.layers.Dropout(0.3),
        keras.layers.Dense(10, activation = 'relu'),
        keras.layers.Dropout(0.2),
        keras.layers.Dense(1, activation = 'sigmoid')]
    )

    model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

    model.fit(X_train, Y_train, epochs = 20, batch_size = 8)

    model.evaluate(X_test,Y_test)

    Y_pred = model.predict(X_test).reshape(-1)
    Y_pred = np.round(Y_pred)

    def accuracy_calculator(y_pred, y_test):
        counts = np.zeros((len(y_pred)),)
        for i in range(len(y_pred)):
            if y_pred[i] != Y_test[i]:
                counts[i] = 1
            else:
                continue
        return 1- sum(counts)/len(counts)

    print()
    print(accuracy_calculator(Y_pred,Y_test))

    error_array[i] = accuracy_calculator(Y_pred,Y_test)


np.mean(error_array)
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(Y_test, Y_pred))

Epoch 1/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.5592 - loss: 0.7193
Epoch 2/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.4105 - loss: 0.7153
Epoch 3/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5145 - loss: 0.6903 
Epoch 4/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4818 - loss: 0.6979 
Epoch 5/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.5323 - loss: 0.6860
Epoch 6/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - accuracy: 0.5770 - loss: 0.6928
Epoch 7/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - accuracy: 0.4922 - loss: 0.6847
Epoch 8/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 763us/step - accuracy: 0.6749 - loss: 0.6515
Epoch 9/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.5803 - loss: 0.6698
Epoch 10/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - accuracy: 0.5945 - loss: 0.6814
Epoch 11/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.5818 - loss: 0.6750
Epoch 12/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - a

In [95]:
print(np.mean(error_array))
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(Y_test, Y_pred))

0.7365384615384616
              precision    recall  f1-score   support

         0.0       0.73      0.89      0.80        27
         1.0       0.84      0.64      0.73        25

    accuracy                           0.77        52
   macro avg       0.78      0.76      0.76        52
weighted avg       0.78      0.77      0.77        52



In [239]:
initialized_matrix = np.array([[3,0,1,2,7,4],[1,5,8,9,3,1],[2,7,2,5,1,3],[0,1,3,1,7,8],[4,2,1,6,2,8],[2,4,5,2,3,9]])

filter = np.array([[1,0,-1],[1,0,-1],[1,0,-1]])

diff_rows, diff_cols = np.array(np.shape(initialized_matrix)) - np.array(np.shape(filter))+ np.array([1,1])

output_conv = np.zeros((diff_rows,diff_cols),)
for i in range(diff_rows):
    for j in range(diff_cols):
        output_conv[i, j] = np.dot(initialized_matrix[i:diff_rows-1+i, j:diff_cols-1+j].flatten(), filter.flatten())


output_conv = np.vstack((output_conv,np.array([-6,-3,0,2])))

print(output_conv)
filter_size = 2
stride = 2

for i in range(filter_size):
    for j in range(filter_size):
        if filter_size+i*stride<= np.shape(output_conv)[0] and filter_size+j*stride <=np.shape(output_conv)[1]:
            print(output_conv[i*stride:filter_size+i*stride, j*stride:filter_size+j*stride])
            print(filter_size+i*stride)

        # output_mat[i, j] = max(output_conv[filter_size*i:filter_size*i+stride, filter_size*j:filter_size*j+stride].flatten())
np.shape(output_conv)[0]
# output_mat

[[ -5.  -4.   0.   8.]
 [-10.  -2.   2.   3.]
 [  0.  -2.  -4.  -7.]
 [ -3.  -2.  -3. -16.]
 [ -6.  -3.   0.   2.]]
[[ -5.  -4.]
 [-10.  -2.]]
2
[[0. 8.]
 [2. 3.]]
2
[[ 0. -2.]
 [-3. -2.]]
4
[[ -4.  -7.]
 [ -3. -16.]]
4


5

In [149]:
a =  np.array([[5,1],[8,2]])

a = np.array([1,2])
b = np.array([3,4])

11